// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

function getSumOfFibonacciNumbers(limit, termA, termB, sum) {
	sum = sum || 0;
  var nextTerm = termA + termB;
  
  if (termA % 2 === 0) {
    sum += termA;
  }

  if (nextTerm < limit) {
    getSumOfFibonacciNumbers(limit, nextTerm, termA, sum);
  } else {
    return sum;
  }
}

getSumOfFibonacciNumbers(4000000, 1, 1);